<?php
/**
 * @author Dmitry Stepanov <dmitry@stepanov.lv>
 * @copyright 2013, Dmitry Stepanov. All rights reserved.
 * @link http://stepanov.lv
 */

use \Core\Input;
use \Core\XHTML;
use \RTK\Template;
use \RTK\Application;

/* @var $app Application */
/* @var $this Template */

?>
<ul class="items">
    <li class="item"><!--
     --><span class="name">Maize &quot;Maigā&quot;</span>,
        <span class="qty">1gab.</span>,
        <span class="total"><!--
         --><span class="currency">Ls</span>
            <span class="value">0,-</span><!--
     --></span>
    </li>
</ul>