<?php
/**
 * @author Dmitry Stepanov <dmitry@stepanov.lv>
 * @copyright 2013, Dmitry Stepanov. All rights reserved.
 * @link http://stepanov.lv
 */

use \Core\Input;
use \Core\XHTML;
use \RTK\Template;
use \RTK\Application;

/* @var $app Application */
/* @var $this Template */

?>
<section class="cart" data-items="0">
    <?php $this->Insert( 'Items' ); ?>
    <p class="summary">
        <?php $this->Insert( 'Total' ); ?>
        <?php $this->Insert( 'Actions' ); ?>
    </p>
</section>