<?php
/**
 * @author Dmitry Stepanov <dmitry@stepanov.lv>
 * @copyright 2013, Dmitry Stepanov. All rights reserved.
 * @link http://stepanov.lv
 */

use \RTK\Template;
use \RTK\Application;

/* @var $app Application */
/* @var $this Template */

?>
<header>
    <h2>Piegāde tikai Rīgas robežās</h2>
</header>
<section class="text">
    <p>
        Pirms piegāde tiek veikta, mūsu operators sazināsies ar Jums lai apstiprinātu Jūsu veikto pasūtījumu.
    </p>
    <p>
        Pasūtījumi tiek apstrādāti 4 stundu laikā un piegādāti uz Rīgas pilsētas robežās noteikto
        adresi 2 stundu laikā kopš pasūtījuma apstiprināšanas.
    </p>
</section>